### ISSUE TITLE
plugins not showing up

### ISSUE THREAD

**Issue by Eisenhuth** [kalilistic/xivplugins#17]
probably the same issue as #14 , though previously one of my plugins (https://github.com/Eisenhuth/dalamud-nael) was in the list, they are now all not showing up

- https://github.com/Eisenhuth/dalamud-nael
- https://github.com/Eisenhuth/dalamud-restart
- https://github.com/Eisenhuth/dalamud-chatgpt

[the Custom Repository they are listed in](https://github.com/Eisenhuth/TrustworthyDalamudPlugins), however, _does_ show up in the Repository list

**Comment by kalilistic** [comment]
Fixed these plugins by adding them to the manual list. Plugins get removed if they don't show up in GitHub searches for a certain number of days in a row.

I'm going to try and make the search more robust - sometimes it misses plugins due to problems with the GitHub API.

**Comment by Eisenhuth** [comment]
seems like something is going wrong with the search API, the plugins above are listed, but the repository doesn't show up
- https://github.com/Eisenhuth/dalamud-logchamp is also missing (though it is pretty new and might just not be indexed yet?)

**Comment by kalilistic** [comment]
yeah, I have some plans to improve the search API. For some reason, I don't get all of these results in the GitHub code search API. My workaround, for now, is to add any manually that people reported missing. I've added dalamud-logchamp and should show up over the next day or so.
