### ISSUE TITLE
plugins not showing up

### ISSUE THREAD

**Issue by Samaelyokus** [kalilistic/xivplugins#18]
Hello, I wanted to ask if anyone knows if these plugins are already obsolete or if they can be installed through another repro or a page to find the links since with the update they can no longer be used.

Thank you in advance for any possible response.

auto jail marker  
Boss Mod
aether compass
beachcomber 
cammy
collector s anxiety
crossup
expanded search info
hilda te dice que mov usar
hud manager
hunt helper
mastercraf
midibard2
naeld it for ucob
noclippy
palace pal
positional assistant
price insight
reaction
the great separator
workhop optimizer plugin

**Comment by kalilistic** [comment]
This repo is just for reporting issues with the website xivplugins. For the plugins themselves, you'd need to go to their respective support channels. Many of these are on the main repo though and have been updated so there might be something with your installation. I'd recommend disabling all third-party plugins and seeing if that works. If it still doesn't work, can ask for help on the goat place discord.
