### ISSUE TITLE
ReShade Shaders search integration feature request

### ISSUE THREAD

**Issue by mrzepher67** [kalilistic/xivplugins#19]
Would it be possible to incorporate a similar search/feed for ffxiv reshade shaders upkept on git similar to the way the api is aggregating plugin repos?

**Comment by kalilistic** [comment]
Hey, it's an interesting idea. Do you have a few examples you'd expect to show up in the list?

**Comment by mrzepher67** [comment]
There are a couple Ive watched on my own in the past

https://github.com/GarrettGunnell/AcerolaFX
https://github.com/ipsusu/IpsuShade
https://github.com/preyx/stormshade-preyx

A lot of the community ones that have been put up on github are likely to be labeled under Gshade, or older ones might be under Stormshade and not necessarily ReShade with an FFXIV tag

**Comment by kalilistic** [comment]
I played with this a bit but having trouble finding a good code search to use. I get back either millions of results and/or a lot of junk. Could always make it a manual list of URLs. That would still let people see when there's updates but wouldn't be as good for discovery.

**Comment by kalilistic** [comment]
Going to close this for now, but if anyone has ideas on a good code search query, feel free to reach out.
