### ISSUE TITLE
Dalamud Crashing since three Days 

### ISSUE THREAD

**Issue by Alpacamutti** [kalilistic/xivplugins#20]
![Screenshot_277](https://user-images.githubusercontent.com/127700464/224581187-d99fd328-c71f-437d-8e4b-6d458ee6cfed.png)

Got since three Days always crashing with this error... 
It's something I can do?

**Comment by kalilistic** [comment]
This repo is just for the website xivplugins. Can join the XIVLauncher Discord for help with this. https://discord.gg/3NMcUV5
