### ISSUE TITLE
Suggestion if possible

### ISSUE THREAD

**Issue by sirsygnus** [kalilistic/xivplugins#21]
Im not a coder but if it possible to create a plugin for dalamud that will illuminate the item i search in my retainers. exemple: i have my clothes retainer open and i search for item (dwarven cotton) from my recipe, it will automaticly illuminate the materiel in question. This way it can be easier for a crafter to gather all the items he need... Well thanks to hear me out.  
![image](https://user-images.githubusercontent.com/129560712/229248397-3b57ed64-b4f2-497b-9288-3c2a2c77dde6.png)

**Comment by kalilistic** [comment]
This repo is just for the website xiv plugins. Can join the XIVLauncher Discord for help. https://discord.gg/3NMcUV5
The Allagan Tools plugin (on main repo) might help though.
