### ISSUE TITLE
Repo there but Plugin missing

### ISSUE THREAD

**Issue by Jukkales** [kalilistic/xivplugins#22]
Hey,

Just wanted to ask if i need to do something special to have my plugin added. 
My repo is found unter Dalamud Repos but my plugin isnt under Plugins :/

repo: `https://raw.githubusercontent.com/Jukkales/DalamudPlugins/master/repo.json`
missing `plugin: https://github.com/Jukkales/NecroLens`

**Comment by kalilistic** [comment]
Hey - occasionally there's been a few plugins that don't show up on the github API calls for some reason. I have plans to improve the site and some extra checks to hopefully avoid this. In the meantime, I've added the plugin to a manual list so should show up later this weekend.

**Comment by kalilistic** [comment]
Fixed, it's now listed.
