### ISSUE TITLE
(Some) plugins listed and repository not listed.

### ISSUE THREAD

**Issue by thakyZ** [kalilistic/xivplugins#24]
My repository wasn't listed and only some of my plugins were listed. Not sure if there is something I need to do on my end. Though, I would like to let you know, just in case I or you need to do something.

**Comment by kalilistic** [comment]
Hey, I've created a master issue for this. There's something with the GitHub API (maybe heavy caching?) where I don't always get back plugins/repos. I have some improvements planned but I can add it manually in the meantime to get it listed. https://github.com/kalilistic/xivplugins/issues/26
