### ISSUE TITLE
Can't find a plugin/repo? Read this!

### ISSUE THREAD

**Issue by kalilistic** [kalilistic/xivplugins#26]
There are some issues with the GitHub API where some plugins/repos aren't being returned. I have some ideas on how to improve this.

In the meantime, please post the plugin/repo url here and I'll manually add it to XIVPlugins. After I do so, you should see the update within 24 hours or so.

**Comment by yschuurmans** [comment]
A few months ago I created a central repo for my plugins, and initially I figured that it would get scanned eventually anyway. After recently noticing that this repo, and one plugin that only exists in this repo has still not been picked up after several months, I am wondering how you query for plugins.

Is there a limit to one repo per github user or something similar?

Besides my curiosity; There is currently still a (dead) link to my old repo: https://github.com/yschuurmans/FFXIVMoneyTracker/raw/master/repo.json

And my new repo is still missing:
https://github.com/yschuurmans/MyDalamudPlugins/raw/master/pluginmaster.json

Along with one missing plugin that is provided by the above repo:
https://github.com/yschuurmans/CardsPls

**Comment by thakyZ** [comment]
If you could remove these repos and if you have a way to do so, blacklist these from being re-added, as they are just auto generated from being forks of the parent repos:
- [thakyZ/LMeter@`main`/repo.json (raw)](https://github.com/thakyZ/LMeter/raw/main/repo.json)
- [thakyZ/LMeter@`personal`/repo.json (raw)](https://github.com/thakyZ/LMeter/raw/personal/repo.json)
- [thakyZ/Glamourer@`main`/repo.json (raw)](https://github.com/thakyZ/Glamourer/raw/main/repo.json)
- [thakyZ/Glamourer@`personal`/repo.json (raw)](https://github.com/thakyZ/Glamourer/raw/personal/repo.json)
- [thakyZ/Glamourer@`rework`/repo.json (raw)](https://github.com/thakyZ/Glamourer/raw/rework/repo.json)
- [thakyZ/PenumbraModForwarder@`master`/repo.json (raw)](https://github.com/thakyZ/PenumbraModForwarder/raw/master/repo.json)
- [thakyZ/PenumbraModForwarder@`personal`/repo.json (raw)](https://github.com/thakyZ/PenumbraModForwarder/raw/personal/repo.json)
- [thakyZ/PenumbraModForwarder@`registry_fix`/repo.json (raw)](https://github.com/thakyZ/PenumbraModForwarder/raw/registry_fix/repo.json)
- [thakyZ/ffxiv_materialui_accent@`master`/repo.json (raw)](https://github.com/thakyZ/ffxiv_materialui_accent/raw/master/repo.json)
- [thakyZ/ffxiv_materialui_accent@`testing`/repo.json (raw)](https://github.com/thakyZ/ffxiv_materialui_accent/raw/testing/repo.json)
- [thakyZ/FFXIV_Vibe_Plugin@`master`/repo.json (raw)](https://github.com/thakyZ/FFXIV_Vibe_Plugin/raw/master/repo.json)
- [thakyZ/XIVSlothCombo@`main`/pluginmaster.json (raw)](https://github.com/thakyZ/XIVSlothCombo/raw/main/pluginmaster.json)
- [thakyZ/XIVSlothCombo@`personal`/pluginmaster.json (raw)](https://github.com/thakyZ/XIVSlothCombo/raw/personal/pluginmaster.json)
- [thakyZ/ffxiv_materialui_accent@`penumbra_alpha`/repo.json (raw)](https://github.com/thakyZ/ffxiv_materialui_accent/raw/penumbra_alpha/repo.json)

Additionally, I don't see my public repo for plugins which I would like added:
- [thakyZ/MyDalamudPlugins@`main`/pluginmaster.json (raw)](https://github.com/thakyZ/MyDalamudPlugins/raw/main/pluginmaster.json)

**Comment by kalilistic** [comment]
> If you could remove these repos and if you have a way to do so, blacklist these from being re-added, as they are just auto generated from being forks of the parent repos:
> 
>     * [thakyZ/LMeter@`main`/repo.json (raw)](https://github.com/thakyZ/LMeter/raw/main/repo.json)
> 
>     * [thakyZ/LMeter@`personal`/repo.json (raw)](https://github.com/thakyZ/LMeter/raw/personal/repo.json)
> 
>     * [thakyZ/Glamourer@`main`/repo.json (raw)](https://github.com/thakyZ/Glamourer/raw/main/repo.json)
> 
>     * [thakyZ/Glamourer@`personal`/repo.json (raw)](https://github.com/thakyZ/Glamourer/raw/personal/repo.json)
> 
>     * [thakyZ/Glamourer@`rework`/repo.json (raw)](https://github.com/thakyZ/Glamourer/raw/rework/repo.json)
> 
>     * [thakyZ/PenumbraModForwarder@`master`/repo.json (raw)](https://github.com/thakyZ/PenumbraModForwarder/raw/master/repo.json)
> 
>     * [thakyZ/PenumbraModForwarder@`personal`/repo.json (raw)](https://github.com/thakyZ/PenumbraModForwarder/raw/personal/repo.json)
> 
>     * [thakyZ/PenumbraModForwarder@`registry_fix`/repo.json (raw)](https://github.com/thakyZ/PenumbraModForwarder/raw/registry_fix/repo.json)
> 
>     * [thakyZ/ffxiv_materialui_accent@`master`/repo.json (raw)](https://github.com/thakyZ/ffxiv_materialui_accent/raw/master/repo.json)
> 
>     * [thakyZ/ffxiv_materialui_accent@`testing`/repo.json (raw)](https://github.com/thakyZ/ffxiv_materialui_accent/raw/testing/repo.json)
> 
>     * [thakyZ/FFXIV_Vibe_Plugin@`master`/repo.json (raw)](https://github.com/thakyZ/FFXIV_Vibe_Plugin/raw/master/repo.json)
> 
>     * [thakyZ/XIVSlothCombo@`main`/pluginmaster.json (raw)](https://github.com/thakyZ/XIVSlothCombo/raw/main/pluginmaster.json)
> 
>     * [thakyZ/XIVSlothCombo@`personal`/pluginmaster.json (raw)](https://github.com/thakyZ/XIVSlothCombo/raw/personal/pluginmaster.json)
> 
>     * [thakyZ/ffxiv_materialui_accent@`penumbra_alpha`/repo.json (raw)](https://github.com/thakyZ/ffxiv_materialui_accent/raw/penumbra_alpha/repo.json)
> 
> 
> Additionally, I don't see my public repo for plugins which I would like added:
> 
>     * [thakyZ/MyDalamudPlugins@`main`/pluginmaster.json (raw)](https://github.com/thakyZ/MyDalamudPlugins/raw/main/pluginmaster.json)

Pushed a fix. Should update tonight or so. I'll take a look after the weekend to double check too. In the next version, I should improve the repo logic to filter out some noise like unmodified plugin master forks.

**Comment by AtmoOmen** [comment]
It's been around two weeks, but my plugin still hasn't shown up on XIVPlugins yet. Thanks for attention to this and taking the time to check it out:
https://github.com/AtmoOmen/CurrencyTracker

**Comment by ssoe** [comment]
https://github.com/zw3lf/ffxiv-coord-importer
bulk import coordinates plugin

**Comment by mnn** [comment]
Hello, could you please add my repo (and ideally plugins in it)? I hope it being on gitlab won't be a problem.

https://gitlab.com/monnef/dalamud-plugin-repo ([link to plugin master json file](https://gitlab.com/monnef/dalamud-plugin-repo/-/raw/master/master.json))

**Comment by kalilistic** [comment]
I've added all these (including the GitLab). May just take a bit to show up on the site. Thanks!

**Comment by Deccentric** [comment]
Whenever you get a chance could you please add my repo please: 
https://raw.githubusercontent.com/Deccentric/Dalamud-Depot/main/repo.json

I only have one plugin underneath it: https://github.com/Deccentric/WhatchaSay/tree/master

I really appreciate your project, thank you 😃

**Comment by kalilistic** [comment]
Added carvelli's repo and Dec's repo + plugin. Should show up after a little bit.

That's a good point about some fields not really making sense for non-gh plugins. I'll consider this as part of the next release. https://github.com/kalilistic/xivplugins/issues/27

**Comment by serifas** [comment]
When possible, I just finished the initial version of my plugin Infinite Roleplay. 
Please add it if you get the chance
https://github.com/serifas/InfiniteRP/blob/main/infinite.json

**Comment by serifas** [comment]
heya could you add my repo to the list please 
https://raw.githubusercontent.com/serifas/AbsoluteRoleplay/main/absolute_rp.json

**Comment by kalilistic** [comment]
> heya could you add my repo to the list please https://raw.githubusercontent.com/serifas/AbsoluteRoleplay/main/absolute_rp.json

Updated, may take a day or so to show up.

**Comment by serifas** [comment]
thank you!

**Comment by serifas** [comment]
Heya just a heads up, I should have posted this a while ago, sorry. 
The absolute roleplay repo is now under dalamud testing builds and the old repo is no longer supported.

**Comment by anya-hichu** [comment]
Haii, please add my repo:
```
https://raw.githubusercontent.com/anya-hichu/DalamudPluginRepo/main/custom.json
````
Thankies

**Comment by kalilistic** [comment]
The latest requests were all added. I've also released a new version of the site that should be better about this.

For future requests, please refer to a self-service process on the README. You can open a new issue if you run into issues or need help.
